### ISSUE TITLE
Navbar Improvement 

### ISSUE THREAD

**Issue by SubhamB2003** [UBA-GCOEN-23/StichHub#10]
The navbar is not looking great whenever I scroll the page so I have an idea to make it look great.
Here it is,

Previous
![image](https://github.com/UBA-GCOEN-23/StichHub/assets/94003231/a64117da-1e07-4cd4-9bf8-ef7b44aacebb)

After Change
![image](https://github.com/UBA-GCOEN-23/StichHub/assets/94003231/c7e38744-da0b-4fe0-b5aa-e00847b5e45e)
Adding a blur effect

Please assign this task to me under GSSOC 23. I would love to work on it.

**Comment by SubhamB2003** [comment]
@Siddhant-Patil0203 Hey, can I start working on it?

**Comment by Naresh-chandanbatve** [comment]
This is not the correct repo for stichub GSSoC23
correct repo: https://github.com/UBA-GCOEN/StichHub

**Comment by SubhamB2003** [comment]
> This is not the correct repo for stichub GSSoC23 correct repo: https://github.com/UBA-GCOEN/StichHub

Oh thanks for correcting me
